 [format]
# Deduplicate icons if enable.
# A superscripted counter will be added.
dedup = true
# window delimiter
delim = " "

# available formatter:
# {counter_sup} - superscripted count of clients on the workspace, and simple {counter}, {delim}
# {icon}, {client}
# workspace formatter
workspace = "{id}:{delim}{clients}" # {id}, {delim} and {clients} are supported
#workspace_empty = "{id}" # {id}, {delim} and {clients} are supported
#workspace_empty = "{id}-{name}:</span></b>{delim}{clients}"
# client formatter
client = "{icon}"
client_active = "|{icon}|"

# deduplicate client formatter
 client_fullscreen = "[{icon}]"
 client_dup = "{client}{counter_sup}"
 client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused}"
 client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused}"

[icons]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"DEFAULT" = ""
"(?i)Kitty" = ""
"[Ff]irefox" = ""
"(?i)waydroid.*" = "droid"
bleachbit = ""
burp-startburp = ""
calibre-gui = ""
"chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default" = ""
chromium = ""
"Gimp-2.10" = ""
code-oss = ""
cssh = ""
darktable = ""
discord = ""
dmenu-clipboard = ""
dmenu-pass = ""
duolingo = ""
element = ""
fontforge = ""
gcr-prompter = ""
gsimplecalc = ""
"jetbrains-studio" = ""
"kak" = ""
kicad = ""
"(?i)waydroid.*" = "droid"
obsidian = ""
"dmenu-emoji" = ""
"dmenu-browser" = ""
"dmenu-pass generator" = ""
"qalculate-gtk" = ""
krita = ""
libreoffice-calc = ""
libreoffice-impress = ""
libreoffice-startcenter = ""
libreoffice-writer = ""
molotov = ""
mpv = ""
neomutt = ""
nm-connection-editor = ""
org-ksnip-ksnip = ""
org-pwmt-zathura = ""
org-qutebrowser-qutebrowser = ""
org-telegram-desktop = ""
paperwork = ""
pavucontrol = ""
personal = ""
plexamp = ""
qutepreview = ""
rapid-photo-downloader = ""
remote-viewer = ""
sandboxed-tor-browser = ""
scli = ""
shopping = ""
Signal = ""
slack = ""
snappergui = ""
songrec = ""
spotify = ""
steam = ""
streamlink-twitch-gui = ""
sun-awt-x11-xframepeer = ""
swappy = ""
taskwarrior-tui = ""
telegramdesktop = ""
".*transmission.*" = ""
udiskie = ""
vimiv = ""
virt-manager = ""
vlc = ""
vncviewer = ""
wayvnc = "󰀄"
whatsapp-desktop = ""
whatsapp-nativefier-d52542 = ""
wire = "󰁀"
wireshark-gtk = ""
wlfreerdp = "󰀄"
work = ""
xplr = ""
nemo = ""
zoom = ""

[icons_active]
DEFAULT = ""
#"(?i)kitty" = "<span foreground='red'>{}</span>"

[title."(?i)kitty"]
"(?i)neomutt" = "neomutt"

[title_active."(?i)firefox"]
"(?i)twitch" = "<span color='purple'>--</span>"
"(?i)youtube" = "<span color='red'>-󰗃-</span>"
# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
"(?i)fcitx" = ".*" # will match all title for fcitx
"(?i)TestApp" = "" # will match all title for TestApp
aProgram = "^$" # will match null title for aProgram
"[Ss]team" = "Friends List.*"
"[Ss]team" = "^$" # will match all Steam window with null title (some popup)
